export enum Status {
  CREATED = 'created',
  IN_ORDER = 'in_order',
  COLLECTED = 'collected',
  READY_TO_STORAGE = 'ready_to_storage',
  READY_TO_DELIVERY = 'ready_to_delivery',
  DELIVERED = 'delivered',
  TO_STORAGE = 'to_storage',
  TO_NEXT_VISIT = 'to_next_visit',
  VISITS_DONE = 'visits_done',
  STORAGED = 'storaged',
  LOST = 'lost',
  CANCELED_VISIT = 'canceled_visit',
  DELETED = 'deleted',
  SUSPEND_VISIT = 'suspend_visit',
  RETURNED = 'returned',
  QUEUED = 'queued',
  TO_RETURN = 'to_return',
  CANCELED_CLIENT_TEST = 'canceled_client_test',
  CANCELED_CLIENT_REQUEST = 'canceled_client_request',
  CANCELED_PACKAGE_NOT_FOUND = 'canceled_package_not_found',
  CANCELED_TESTING = 'canceled_testing',
  CANCELED_DUPLICATED_PACKAGE = 'canceled_duplicated_package',
  IN_PRE_ORDER = 'in_pre_order',
  OUT_PRE_ORDER = 'out_pre_order',
  QUEUED_FOR_ROUTING = 'queued_for_routing',
  AUDIT = 'audit',
}
