version: "3.6"
services:
  feather-api-postgres:
    container_name: feather-api-postgres
    image: postgres
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      PGDATA: /data/postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5440:5432"
    networks:
      - postgres_network
    restart: unless-stopped

networks:
  postgres_network:
    name: postgres_network
    driver: bridge
